=== gitblanc/SEW/Prácticas/XML/Program/persona.dtd
<!ELEMENT redSocial (persona+)>
<!ELEMENT persona (datos,(persona,persona,persona)?)>
<!ELEMENT datos (nombre, apellidos,fecha,lugar_nacimiento,coordenadas_nacimiento,lugar_residencia,coordenadas_residencia,fotografia+,video*, comentarios)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT lugar_nacimiento (#PCDATA)>
<!ELEMENT coordenadas_nacimiento (#PCDATA)>
<!ELEMENT lugar_residencia (#PCDATA)>
<!ELEMENT coordenadas_residencia (#PCDATA)>
<!ELEMENT fotografia (#PCDATA)>
<!ELEMENT video (#PCDATA)>
<!ELEMENT comentarios (#PCDATA)>

=== gitblanc/SEW/Prácticas/XML/Program/xml.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE redSocial SYSTEM "persona.dtd">
<redSocial>
	<persona>
		<datos>
			<nombre>Eduardo</nombre>
			<apellidos>Blanco Bielsa</apellidos>
			<fecha>09/03/2002</fecha>
			<lugar_nacimiento>Barcelona</lugar_nacimiento>
			<coordenadas_nacimiento>41.52988683790763, 2.0653854852963143,0</coordenadas_nacimiento>
			<lugar_residencia>Barcelona</lugar_residencia>
			<coordenadas_residencia>41.56067105642616, 1.5003019989289033, 0</coordenadas_residencia>
			<fotografia><![CDATA[https://www.ecestaticos.com/imagestatic/clipping/bdb/7f2/bdb7f290c31649600550ed00041c7d84/los-10-rasgos-que-indican-que-eres-una-persona-mas-inteligente-que-los-demas.jpg?mtime=1472142151]]></fotografia>
			<video><![CDATA[https://www.bing.com/videos/search?q=python&&view=detail&mid=1545C93E75B4E16939161545C93E75B4E1693916&&FORM=VRDGAR&ru=%2Fvideos%2Fsearch%3Fq%3Dpython%26FORM%3DHDRSC4]]></video>
			<video><![CDATA[https://www.bing.com/videos/search?q=python&&view=detail&mid=1545C93E75B4E16939161545C93E75B4E1693916&&FORM=VRDGAR&ru=%2Fvideos%2Fsearch%3Fq%3Dpython%26FORM%3DHDRSC4]]></video>
			<comentarios>Buen programador</comentarios>
		</datos>
		<persona>
			<datos>
				<nombre>Maria</nombre>
				<apellidos>Estrada Muniz</apellidos>
				<fecha>15/06/2002</fecha>
				<lugar_nacimiento>Aviles</lugar_nacimiento>
				<coordenadas_nacimiento>43.53648741128185, -5.919837069722076, 0</coordenadas_nacimiento>
				<lugar_residencia>Aviles</lugar_residencia>
				<coordenadas_residencia>43.53648741128185, -5.919837069722076, 0</coordenadas_residencia>
				<fotografia><![CDATA[https://13543refcewf-5b7f43b3f441dd62d4a9a80fa556390f-1200x800-3882242465.jpg]]></fotografia>
				<video><![CDATA[https://www.bing.com/videos/search?q=avil%c3%a9s&&view=detail&mid=3B5AB39884E40920588A3B5AB39884E40920588A&&FORM=VRDGAR&ru=%2Fvideos%2Fsearch%3Fq%3Davil%25c3%25a9s%26FORM%3DHDRSC4]]></video>
				<comentarios>Muy guapa</comentarios>
			</datos>
			<persona>
				<datos>
					<nombre>Killian</nombre>
					<apellidos>Perez Gonzalez</apellidos>
					<fecha>17/06/1992</fecha>
					<lugar_nacimiento>Grado</lugar_nacimiento>
					<coordenadas_nacimiento>43.53648741128185, -5.919837069722076, 0</coordenadas_nacimiento>
					<lugar_residencia>Grado</lugar_residencia>
					<coordenadas_residencia>43.53648741128185, -5.919837069722076, 0</coordenadas_residencia>
					<fotografia><![CDATA[https://ath2.unileverservices.com/wp-content/uploads/sites/13/2019/12/19172351/pelo-platinado-para-hombre-61-1024x1024.jpg]]></fotografia>
					<video><![CDATA[https://www.bing.com/videos/search?q=nissan+gtr&&view=detail&mid=5027A94DFD224ED971D85027A94DFD224ED971D8&&FORM=VRDGAR&ru=%2Fvideos%2Fsearch%3Fq%3Dnissan%2Bgtr%26FORM%3DHDRSC4]]></video>
					<comentarios>Buen conductor</comentarios>
				</datos>
			</persona>
			<persona>
				<datos>
					<nombre>Paco</nombre>
					<apellidos>Perez Gonzalez</apellidos>
					<fecha>17/06/1992</fecha>
					<lugar_nacimiento>Salinas</lugar_nacimiento>
					<coordenadas_nacimiento>43.56322977597883, -5.97454710877856, 0</coordenadas_nacimiento>
					<lugar_residencia>Salinas</lugar_residencia>
					<coordenadas_residencia>43.56322977597883, -5.97454710877856, 0</coordenadas_residencia>
					<fotografia><![CDATA[https://img.ecartelera.com/noticias/31000/31086-m.jpg]]></fotografia>
					<video><![CDATA[https://www.youtube.com/watch?v=bkUyuN4hD3s]]></video>
					<comentarios>Gran persona</comentarios>
				</datos>
			</persona>
			<persona>
				<datos>
					<nombre>Carlos</nombre>
					<apellidos>Perez Gonzalez</apellidos>
						<fecha>17/06/1993</fecha>
						<lugar_nacimiento>Arriondas</lugar_nacimiento>
						<coordenadas_nacimiento>43.35821014744797, -5.198427950070287, 0</coordenadas_nacimiento>
						<lugar_residencia>Arriondas</lugar_residencia>
						<coordenadas_residencia>43.35821014744797, -5.198427950070287, 0</coordenadas_residencia>
						<fotografia><![CDATA[http://grupojosvil.es/blog/wp-content/uploads/2016/02/americana-para-hombre-portada.jpg]]></fotografia>
						<video><![CDATA[https://www.youtube.com/watch?v=bRI5--UmHxo]]></video>
						<comentarios>Gran persona</comentarios>
				</datos>
			</persona>
		</persona>
		<persona>
			<datos>
				<nombre>Chen Xin</nombre>
				<apellidos>Pan Wang</apellidos>
				<fecha>15/06/2001</fecha>
				<lugar_nacimiento>Mieres</lugar_nacimiento>
				<coordenadas_nacimiento>43.24246527762923, -5.7684302174494775, 0</coordenadas_nacimiento>
				<lugar_residencia>Mieres</lugar_residencia>
				<coordenadas_residencia>43.24246527762923, -5.7684302174494775, 0</coordenadas_residencia>
				<fotografia><![CDATA[https://image.freepik.com/free-photo/femenino-morena-personas-mujer-parque_1301-1415.jpg]]></fotografia>
				<video><![CDATA[https://www.bing.com/videos/search?q=fideos+chinos&&view=detail&mid=3F1C4671E86031F47A9B3F1C4671E86031F47A9B&&FORM=VRDGAR&ru=%2Fvideos%2Fsearch%3Fq%3Dfideos%2Bchinos%26FORM%3DHDRSC4]]></video>
				<comentarios>No sabe cocinar</comentarios>
			</datos>
			<persona>
				<datos>
					<nombre>Luis</nombre>
					<apellidos>Perez Gonzalez</apellidos>
					<fecha>17/06/1998</fecha>
					<lugar_nacimiento>Belmonte</lugar_nacimiento>
					<coordenadas_nacimiento>43.28045387817449, -6.2366463656538125, 0</coordenadas_nacimiento>
					<lugar_residencia>Belmonte</lugar_residencia>
					<coordenadas_residencia>43.28045387817449, -6.2366463656538125, 0</coordenadas_residencia>
					<fotografia><![CDATA[https://www.tuotrodiario.com/images/0265-1148b4f9c07a-151b524bc576-1000/horizontal-1200/felix-kjellberg-conocido-como-pewdiepie.jpg]]></fotografia>
					<video><![CDATA[https://youtu.be/IJx0hLQEf2k]]></video>
					<comentarios>Buen conductor</comentarios>
				</datos>
			</persona>
			<persona>
				<datos>
					<nombre>Marcos</nombre>
					<apellidos>Perez Perez</apellidos>
					<fecha>17/06/1989</fecha>
					<lugar_nacimiento>Proaza</lugar_nacimiento>
					<coordenadas_nacimiento>43.249879548784264, -5.994904332613531, 0</coordenadas_nacimiento>
					<lugar_residencia>Proaza</lugar_residencia>
					<coordenadas_residencia>43.249879548784264, -5.994904332613531, 0</coordenadas_residencia>
					<fotografia><![CDATA[https://www.modalia.es/wp-content/uploads/2015/03/zalando-estilos-hombre-portada.jpg]]></fotografia>
					<video><![CDATA[https://www.youtube.com/watch?v=NJVoa02S3Bg]]></video>
					<comentarios>Gran persona</comentarios>
				</datos>
			</persona>
			<persona>
				<datos>
					<nombre>Carla</nombre>
					<apellidos>Perez Gonzalez</apellidos>
					<fecha>17/06/2000</fecha>
					<lugar_nacimiento>Pola de Siero</lugar_nacimiento>
					<coordenadas_nacimiento>43.399824356920135, -5.684456669130222, 0</coordenadas_nacimiento>
					<lugar_residencia>Pola de Siero</lugar_residencia>
					<coordenadas_residencia>43.399824356920135, -5.684456669130222, 0</coordenadas_residencia>
					<fotografia><![CDATA[https://static.americadigital.com/wp-content/uploads/2020/10/americadigital_mujer_feliz_58_2020-1140x570.jpg]]></fotografia>
					<video><![CDATA[https://youtu.be/06jJo1UhKXU]]></video>
					<comentarios>Gran persona</comentarios>
				</datos>
			</persona>
		</persona>
		<persona>
			<datos>
				<nombre>Alejandro</nombre>
				<apellidos>Coalla Martinez</apellidos>
				<fecha>17/06/2003</fecha>
				<lugar_nacimiento>Cadavedo</lugar_nacimiento>
				<coordenadas_nacimiento>43.55032115030053, -6.381691585477982, 0</coordenadas_nacimiento>
				<lugar_residencia>Cadavedo</lugar_residencia>
				<coordenadas_residencia>43.55032115030053, -6.381691585477982, 0</coordenadas_residencia>
				<fotografia><![CDATA[http://4everstatic.com/imagenes/850xX/personas/hombre-134444.jpg]]></fotografia>
				<video><![CDATA[https://www.bing.com/videos/search?q=nissan+gtr&&view=detail&mid=5027A94DFD224ED971D85027A94DFD224ED971D8&&FORM=VRDGAR&ru=%2Fvideos%2Fsearch%3Fq%3Dnissan%2Bgtr%26FORM%3DHDRSC4]]></video>
				<comentarios>Buen conductor</comentarios>
			</datos>
			<persona>
				<datos>
					<nombre>Luis</nombre>
					<apellidos>Perez Gonzalez</apellidos>
					<fecha>17/06/1998</fecha>
					<lugar_nacimiento>Ribadesella</lugar_nacimiento>
					<coordenadas_nacimiento>43.457112703914234, -5.062289015673917, 0</coordenadas_nacimiento>
					<lugar_residencia>Ribadesella</lugar_residencia>
					<coordenadas_residencia>43.457112703914234, -5.062289015673917, 0</coordenadas_residencia>
					<fotografia><![CDATA[https://doloritta.com/images5/1117/peinados-modernos-de-lado-para-hombre/peinados-modernos-de-lado-para-hombre-81_10.jpg]]></fotografia>
					<video><![CDATA[https://youtu.be/IJx0hLQEf2k]]></video>
					<comentarios>Buen conductor</comentarios>
				</datos>
			</persona>
			<persona>
				<datos>
					<nombre>Marcos</nombre>
					<apellidos>Perez Gonzalez</apellidos>
					<fecha>17/06/1989</fecha>
					<lugar_nacimiento>Benia</lugar_nacimiento>
					<coordenadas_nacimiento>43.332302447494754, -4.950324284581576, 0</coordenadas_nacimiento>
					<lugar_residencia>Benia</lugar_residencia>
					<coordenadas_residencia>43.332302447494754, -4.950324284581576, 0</coordenadas_residencia>
					<fotografia><![CDATA[https://image.freepik.com/foto-gratis/hombre-sonriendo-brazos-cruzados_1187-3244.jpg]]></fotografia>
					<video><![CDATA[https://www.youtube.com/watch?v=NJVoa02S3Bg]]></video>
					<comentarios>Gran persona</comentarios>
				</datos>
			</persona>
			<persona>
				<datos>
					<nombre>Lorena</nombre>
					<apellidos>Perez Vidal</apellidos>
					<fecha>17/06/2000</fecha>
					<lugar_nacimiento>Laviana</lugar_nacimiento>
					<coordenadas_nacimiento>43.237830899898434, -5.559768673141023, 0</coordenadas_nacimiento>
					<lugar_residencia>Laviana</lugar_residencia>
					<coordenadas_residencia>43.237830899898434, -5.559768673141023, 0</coordenadas_residencia>
					<fotografia><![CDATA[https://static.diariofemenino.com/uploads/psicologia/216083-mujeres-inspiran.jpg]]></fotografia>
					<video><![CDATA[https://youtu.be/06jJo1UhKXU]]></video>
