=== gitblanc/SEW/Teoría/XML/06-Ejemplos/06-Ejemplos/Python/libros.dtd
<!ELEMENT libros (libro+)>
<!ELEMENT libro  (titulo, autor+, any?, precio, editorial, clasificacion)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT any (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT editorial (#PCDATA)>
<!ELEMENT clasificacion (#PCDATA)>
<!ELEMENT idioma (#PCDATA)>
<!ATTLIST libro isbn ID #REQUIRED>
<!ATTLIST precio moneda CDATA #REQUIRED>

=== gitblanc/SEW/Teoría/XML/06-Ejemplos/06-Ejemplos/Python/libros.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libros SYSTEM "libros.dtd">
<libros>
<libro isbn="ISBN-9788420633114">
<titulo>El Aleph</titulo>
<autor>Jorge Luis Borges</autor>
<any>1946</any>
<precio moneda="Euro">7.80</precio>
<editorial>Alianza Editorial</editorial>
<clasificacion>Literatura</clasificacion>
<idioma>Español</idioma>
</libro>
<libro isbn="ISBN-9780470036662">
<titulo>Domain-Specific Modeling. Enabling full code generation</titulo>
<autor>Steven Kelly</autor>
<autor>Juha-Pekka Tolvanen</autor>
<any>2008</any>
<precio moneda="Dolar USA">74.03</precio>
<editorial>Wiley</editorial>
<clasificacion>Informática</clasificacion>
<idioma>Inglés</idioma>
</libro>
</libros>
