=== gitblanc/SEW/Teoría/XML/06-Ejemplos/06-Ejemplos/Python/libros.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.uniovi.es" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="libros">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="libro">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="titulo" type="xs:string" />
              <xs:element maxOccurs="unbounded" name="autor" type="xs:string" />
              <xs:element name="año" type="xs:unsignedShort" />
              <xs:element name="precio">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:float">
                      <xs:attribute name="moneda" type="xs:string" use="required" />
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="editorial" type="xs:string" />
              <xs:element name="clasificacion" type="xs:string" />
              <xs:element name="idioma" type="xs:string" />
            </xs:sequence>
            <xs:attribute name="isbn" type="xs:ID" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== gitblanc/SEW/Teoría/XML/06-Ejemplos/06-Ejemplos/Python/libros-xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<libros 
xmlns="http://www.uniovi.es"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.uniovi.es libros.xsd"
>
<libro isbn="ISBN-9788420633114">
<titulo>El Aleph</titulo>
<autor>Jorge Luis Borges</autor>
<año>1946</año>
<precio moneda="Euro">7.80</precio>
<editorial>Alianza Editorial</editorial>
<clasificacion>Literatura</clasificacion>
<idioma>Español</idioma>
</libro>
<libro isbn="ISBN-9780470036662">
<titulo>Domain-Specific Modeling. Enabling full code generation</titulo>
<autor>Steven Kelly</autor>
<autor>Juha-Pekka Tolvanen</autor>
<año>2008</año>
<precio moneda="Dolar USA">74.03</precio>
<editorial>Wiley</editorial>
<clasificacion>Informática</clasificacion>
<idioma>Inglés</idioma>
</libro>
</libros>
