<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libros [
<!ELEMENT libros (libro+)>
<!ELEMENT libro  (título, autor+, año?, precio, editorial, clasificación, idioma)>
<!ELEMENT título (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT año (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT editorial (#PCDATA)>
<!ELEMENT clasificación (#PCDATA)>
<!ELEMENT idioma (#PCDATA)>
<!ATTLIST libro isbn ID #REQUIRED>
<!ATTLIST precio moneda CDATA #REQUIRED>
]>
<libros>
<libro isbn="isbn-9788420633114">
<título>El Aleph</título>
<autor>Jorge Luis Borges</autor>
<año>1946</año>
<precio moneda="Euro">7,80</precio>
<editorial>Alianza Editorial</editorial>
<clasificación>Literatura</clasificación>
<idioma>Español</idioma>
</libro>

<libro isbn="isbn-9780470036662">
<título>Domain-Specific Modeling. Enabling full code generation</título>
<autor>Steven Kelly</autor>
<autor>Juha-Pekka Tolvanen</autor>
<año>2008</año>
<precio moneda="Dolar USA">74,03</precio>
<editorial>Wiley</editorial>
<clasificación>Informática</clasificación>
<idioma>Inglés</idioma>
</libro>

</libros>